# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/v2/protoc-gen-connecpy.  DO NOT EDIT!
# source: storage/v1/storage.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connecpy.client import ConnecpyClient, ConnecpyClientSync
from connecpy.code import Code
from connecpy.exceptions import ConnecpyException
from connecpy.interceptor import Interceptor, InterceptorSync
from connecpy.method import IdempotencyLevel, MethodInfo
from connecpy.request import Headers, RequestContext
from connecpy.server import ConnecpyASGIApplication, ConnecpyWSGIApplication, Endpoint, EndpointSync
import storage.v1.storage_pb2 as storage_dot_v1_dot_storage__pb2


class StorageService(Protocol):
    async def agentic_save_file(self, request: AsyncIterator[storage_dot_v1_dot_storage__pb2.SaveFileRequest], ctx: RequestContext) -> storage_dot_v1_dot_storage__pb2.SaveFileResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")

    async def agentic_search(self, request: storage_dot_v1_dot_storage__pb2.SearchRequest, ctx: RequestContext) -> storage_dot_v1_dot_storage__pb2.SearchResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")


class StorageServiceASGIApplication(ConnecpyASGIApplication):
    def __init__(self, service: StorageService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None):
        super().__init__(
            endpoints={
                "/storage.v1.StorageService/AgenticSaveFile": Endpoint.client_stream(
                    method=MethodInfo(
                        name="AgenticSaveFile",
                        service_name="storage.v1.StorageService",
                        input=storage_dot_v1_dot_storage__pb2.SaveFileRequest,
                        output=storage_dot_v1_dot_storage__pb2.SaveFileResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.agentic_save_file,
                ),
                "/storage.v1.StorageService/AgenticSearch": Endpoint.unary(
                    method=MethodInfo(
                        name="AgenticSearch",
                        service_name="storage.v1.StorageService",
                        input=storage_dot_v1_dot_storage__pb2.SearchRequest,
                        output=storage_dot_v1_dot_storage__pb2.SearchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.agentic_search,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self):
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/storage.v1.StorageService"


class StorageServiceClient(ConnecpyClient):
    async def agentic_save_file(
        self,
        request: AsyncIterator[storage_dot_v1_dot_storage__pb2.SaveFileRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> storage_dot_v1_dot_storage__pb2.SaveFileResponse:
        return await self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="AgenticSaveFile",
                service_name="storage.v1.StorageService",
                input=storage_dot_v1_dot_storage__pb2.SaveFileRequest,
                output=storage_dot_v1_dot_storage__pb2.SaveFileResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def agentic_search(
        self,
        request: storage_dot_v1_dot_storage__pb2.SearchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> storage_dot_v1_dot_storage__pb2.SearchResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AgenticSearch",
                service_name="storage.v1.StorageService",
                input=storage_dot_v1_dot_storage__pb2.SearchRequest,
                output=storage_dot_v1_dot_storage__pb2.SearchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class StorageServiceSync(Protocol):
    def agentic_save_file(self, request: Iterator[storage_dot_v1_dot_storage__pb2.SaveFileRequest], ctx: RequestContext) -> storage_dot_v1_dot_storage__pb2.SaveFileResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")
    def agentic_search(self, request: storage_dot_v1_dot_storage__pb2.SearchRequest, ctx: RequestContext) -> storage_dot_v1_dot_storage__pb2.SearchResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")


class StorageServiceWSGIApplication(ConnecpyWSGIApplication):
    def __init__(self, service: StorageServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None):
        super().__init__(
            endpoints={
                "/storage.v1.StorageService/AgenticSaveFile": EndpointSync.client_stream(
                    method=MethodInfo(
                        name="AgenticSaveFile",
                        service_name="storage.v1.StorageService",
                        input=storage_dot_v1_dot_storage__pb2.SaveFileRequest,
                        output=storage_dot_v1_dot_storage__pb2.SaveFileResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.agentic_save_file,
                ),
                "/storage.v1.StorageService/AgenticSearch": EndpointSync.unary(
                    method=MethodInfo(
                        name="AgenticSearch",
                        service_name="storage.v1.StorageService",
                        input=storage_dot_v1_dot_storage__pb2.SearchRequest,
                        output=storage_dot_v1_dot_storage__pb2.SearchResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.agentic_search,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self):
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/storage.v1.StorageService"


class StorageServiceClientSync(ConnecpyClientSync):
    def agentic_save_file(
        self,
        request: Iterator[storage_dot_v1_dot_storage__pb2.SaveFileRequest],
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> storage_dot_v1_dot_storage__pb2.SaveFileResponse:
        return self.execute_client_stream(
            request=request,
            method=MethodInfo(
                name="AgenticSaveFile",
                service_name="storage.v1.StorageService",
                input=storage_dot_v1_dot_storage__pb2.SaveFileRequest,
                output=storage_dot_v1_dot_storage__pb2.SaveFileResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def agentic_search(
        self,
        request: storage_dot_v1_dot_storage__pb2.SearchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> storage_dot_v1_dot_storage__pb2.SearchResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AgenticSearch",
                service_name="storage.v1.StorageService",
                input=storage_dot_v1_dot_storage__pb2.SearchRequest,
                output=storage_dot_v1_dot_storage__pb2.SearchResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
