# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage/v1/storage.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'storage/v1/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18storage/v1/storage.proto\x12\nstorage.v1\"2\n\x0fSaveFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x0c\n\x04part\x18\x02 \x01(\x0c\"\x12\n\x10SaveFileResponse\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"Z\n\x0cSearchResult\x12\x15\n\rdocument_name\x18\x01 \x01(\t\x12\x14\n\x0chtml_content\x18\x02 \x01(\t\x12\x0e\n\x06header\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\";\n\x0eSearchResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.storage.v1.SearchResult2\xa8\x01\n\x0eStorageService\x12N\n\x0f\x41genticSaveFile\x12\x1b.storage.v1.SaveFileRequest\x1a\x1c.storage.v1.SaveFileResponse(\x01\x12\x46\n\rAgenticSearch\x12\x19.storage.v1.SearchRequest\x1a\x1a.storage.v1.SearchResponseB8Z6github.com/mruruk/doc-storage/gen/storage/v1;storagev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage.v1.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/mruruk/doc-storage/gen/storage/v1;storagev1'
  _globals['_SAVEFILEREQUEST']._serialized_start=40
  _globals['_SAVEFILEREQUEST']._serialized_end=90
  _globals['_SAVEFILERESPONSE']._serialized_start=92
  _globals['_SAVEFILERESPONSE']._serialized_end=110
  _globals['_SEARCHREQUEST']._serialized_start=112
  _globals['_SEARCHREQUEST']._serialized_end=157
  _globals['_SEARCHRESULT']._serialized_start=159
  _globals['_SEARCHRESULT']._serialized_end=249
  _globals['_SEARCHRESPONSE']._serialized_start=251
  _globals['_SEARCHRESPONSE']._serialized_end=310
  _globals['_STORAGESERVICE']._serialized_start=313
  _globals['_STORAGESERVICE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
